services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    logging:
      driver: none

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    logging:
      driver: none

volumes:
  postgresdata:
